-- H2 2.1.210;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'b23ea86d5bdc2f07' HASH 'b649f776ae1dda4c85c97478429c311548675c99309deb3baa46cc17a7186fb1' ADMIN;         
CREATE SEQUENCE "PUBLIC"."GEN" START WITH 1 RESTART WITH 1174 INCREMENT BY 50;
CREATE MEMORY TABLE "PUBLIC"."COMMENT"(
    "ID" BIGINT NOT NULL,
    "DATE" TIMESTAMP,
    "TEXT" CHARACTER VARYING(255),
    "USER_ID" BIGINT
);       
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT; 
CREATE MEMORY TABLE "PUBLIC"."COMMENT_TAG"(
    "COMMENT_ID" BIGINT NOT NULL,
    "TAG_ID" BIGINT NOT NULL
);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT_TAG;             
CREATE MEMORY TABLE "PUBLIC"."IWUSER"(
    "ID" BIGINT NOT NULL,
    "ENABLED" BOOLEAN NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLES" CHARACTER VARYING(255),
    "SCORE" DOUBLE PRECISION,
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."IWUSER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.IWUSER;  
INSERT INTO "PUBLIC"."IWUSER" VALUES
(1, TRUE, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'ADMIN,MENTOR,USER', NULL, 'a'),
(2, TRUE, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'USER', NULL, 'b'),
(3, TRUE, NULL, NULL, '{bcrypt}$2a$10$2BpNTbrsarbHjNsUWgzfNubJqBRf.0Vz9924nRSHBqlbPKerkgX.W', 'MENTOR', NULL, 'c'),
(975, TRUE, 'nuevo', 'fernandez', '{bcrypt}$2a$10$D.R19kIKGy.rrbBSC0kJguMxHpIAXPAEw/6GWU/VvgiJTS47Jd0ve', 'USER,MENTOR', 0.0, 'antoniof');      
CREATE MEMORY TABLE "PUBLIC"."IWUSER_COMMENTS"(
    "USER_ID" BIGINT NOT NULL,
    "COMMENTS_ID" BIGINT NOT NULL
);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.IWUSER_COMMENTS;         
CREATE MEMORY TABLE "PUBLIC"."IWUSER_MENTORINGS"(
    "USER_ID" BIGINT NOT NULL,
    "MENTORINGS_ID" BIGINT NOT NULL
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.IWUSER_MENTORINGS;       
CREATE MEMORY TABLE "PUBLIC"."IWUSER_REVIEW"(
    "USER_ID" BIGINT NOT NULL,
    "REVIEW_ID" BIGINT NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.IWUSER_REVIEW;           
CREATE MEMORY TABLE "PUBLIC"."MENTORING"(
    "ID" BIGINT NOT NULL,
    "CLASSROOM" CHARACTER VARYING(255),
    "DATE" TIMESTAMP,
    "FIN" CHARACTER VARYING(255),
    "INI" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "MENTOR_ID" BIGINT
);    
ALTER TABLE "PUBLIC"."MENTORING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.MENTORING;               
INSERT INTO "PUBLIC"."MENTORING" VALUES
(1075, 'aula 2', TIMESTAMP '2022-05-12 00:00:00', '15:44', '14:44', 'lala', 2);      
CREATE MEMORY TABLE "PUBLIC"."MENTORING_ALUMNOS"(
    "MENTORING_ID" BIGINT NOT NULL,
    "ALUMNOS_ID" BIGINT NOT NULL
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENTORING_ALUMNOS;       
CREATE MEMORY TABLE "PUBLIC"."MENTORING_REVIEWS"(
    "MENTORING_ID" BIGINT NOT NULL,
    "REVIEWS_ID" BIGINT NOT NULL
);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENTORING_REVIEWS;       
CREATE MEMORY TABLE "PUBLIC"."MENTORING_TAG"(
    "MENTORING_ID" BIGINT NOT NULL,
    "TAG_ID" BIGINT NOT NULL
);          
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.MENTORING_TAG;           
INSERT INTO "PUBLIC"."MENTORING_TAG" VALUES
(1075, 1025);    
CREATE MEMORY TABLE "PUBLIC"."MESSAGE"(
    "ID" BIGINT NOT NULL,
    "DATE_READ" TIMESTAMP,
    "DATE_SENT" TIMESTAMP,
    "TEXT" CHARACTER VARYING(255),
    "RECIPIENT_ID" BIGINT,
    "SENDER_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_63" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MESSAGE; 
CREATE MEMORY TABLE "PUBLIC"."REVIEW"(
    "ID" BIGINT NOT NULL,
    "SCORE" INTEGER,
    "TEXT" CHARACTER VARYING(255),
    "CREATOR_ID" BIGINT,
    "MENTORING_ID" BIGINT
);          
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8F" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REVIEW;  
CREATE MEMORY TABLE "PUBLIC"."TAG"(
    "ID" BIGINT NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."TAG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TAG;     
INSERT INTO "PUBLIC"."TAG" VALUES
(1025, 'sususu', 'lala');  
CREATE MEMORY TABLE "PUBLIC"."TAG_COMMENT"(
    "TAG_ID" BIGINT NOT NULL,
    "COMMENT_ID" BIGINT NOT NULL
);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG_COMMENT;             
CREATE MEMORY TABLE "PUBLIC"."TAG_MENTORING"(
    "TAG_ID" BIGINT NOT NULL,
    "MENTORING_ID" BIGINT NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG_MENTORING;           
ALTER TABLE "PUBLIC"."IWUSER" ADD CONSTRAINT "PUBLIC"."UK_D2IR61JG0CAX4VX7AB3EA3F9G" UNIQUE("USERNAME");      
ALTER TABLE "PUBLIC"."MENTORING_ALUMNOS" ADD CONSTRAINT "PUBLIC"."UK_PDFMTT4Y7XO1GHOEQI7L810IH" UNIQUE("ALUMNOS_ID");         
ALTER TABLE "PUBLIC"."IWUSER_REVIEW" ADD CONSTRAINT "PUBLIC"."UK_JCCFA2YRIFCPXH6XMI1T2MUV3" UNIQUE("REVIEW_ID");              
ALTER TABLE "PUBLIC"."MENTORING_REVIEWS" ADD CONSTRAINT "PUBLIC"."UK_5KJA7A47NPX5LCG3XESY8GIKI" UNIQUE("REVIEWS_ID");         
ALTER TABLE "PUBLIC"."IWUSER_COMMENTS" ADD CONSTRAINT "PUBLIC"."UK_BUC4PAQ2QFGQBKNQPM1UOB6M0" UNIQUE("COMMENTS_ID");          
ALTER TABLE "PUBLIC"."IWUSER_MENTORINGS" ADD CONSTRAINT "PUBLIC"."UK_NJX9V3NIS2UEFJ6X4YHTCYUV8" UNIQUE("MENTORINGS_ID");      
ALTER TABLE "PUBLIC"."MENTORING_REVIEWS" ADD CONSTRAINT "PUBLIC"."FKES1WE9GCADPL39I0RHYDSFCIA" FOREIGN KEY("MENTORING_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."MENTORING_TAG" ADD CONSTRAINT "PUBLIC"."FKO7Q8VAOQL7J2DL3MXO5G29H1U" FOREIGN KEY("TAG_ID") REFERENCES "PUBLIC"."TAG"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKMCRKG1ES0P1FY3A6SFCA8U4M6" FOREIGN KEY("MENTORING_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MENTORING_ALUMNOS" ADD CONSTRAINT "PUBLIC"."FKFWCH8528EDW26X4HTRQ22SJIJ" FOREIGN KEY("MENTORING_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."MENTORING_REVIEWS" ADD CONSTRAINT "PUBLIC"."FKTBQ161XB42SB92WNHKNQH3XSN" FOREIGN KEY("REVIEWS_ID") REFERENCES "PUBLIC"."REVIEW"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."IWUSER_MENTORINGS" ADD CONSTRAINT "PUBLIC"."FKMXSXJ13Q5R5T6U4OHYNO1T9AL" FOREIGN KEY("MENTORINGS_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."IWUSER_REVIEW" ADD CONSTRAINT "PUBLIC"."FK4C4D3YSOR82MJUHDO7UAFUBWR" FOREIGN KEY("REVIEW_ID") REFERENCES "PUBLIC"."REVIEW"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."TAG_MENTORING" ADD CONSTRAINT "PUBLIC"."FKO6N0HD44QAYBKVNWLKX1TK7TB" FOREIGN KEY("MENTORING_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."MENTORING" ADD CONSTRAINT "PUBLIC"."FK8NWFIC933UHXPY9WFUEA49NQH" FOREIGN KEY("MENTOR_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKR5MDSIQJTCAYN048SJGABKEEI" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."IWUSER_MENTORINGS" ADD CONSTRAINT "PUBLIC"."FK80RN9R74246OVT9C0FC6E4QW0" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."MENTORING_TAG" ADD CONSTRAINT "PUBLIC"."FK562XDVUJ5RKI10SM1JVLOEX97" FOREIGN KEY("MENTORING_ID") REFERENCES "PUBLIC"."MENTORING"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."COMMENT_TAG" ADD CONSTRAINT "PUBLIC"."FK54JB4MIWJ81HFY9UU9SYYJG04" FOREIGN KEY("TAG_ID") REFERENCES "PUBLIC"."TAG"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."TAG_COMMENT" ADD CONSTRAINT "PUBLIC"."FKID6JR2LSI45EPPJN6NDUWWWJX" FOREIGN KEY("TAG_ID") REFERENCES "PUBLIC"."TAG"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."IWUSER_COMMENTS" ADD CONSTRAINT "PUBLIC"."FKK6C9WY8PXKOUBKISDRSS2XFCJ" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKR4NY685DYK21XOBGO0UGUC87Q" FOREIGN KEY("CREATOR_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."FKNCAXW3LCT4F38N1NXO5BCAR54" FOREIGN KEY("RECIPIENT_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."MESSAGE" ADD CONSTRAINT "PUBLIC"."FKXQR9WQ16K3403YBEPWGPGY0N" FOREIGN KEY("SENDER_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TAG_MENTORING" ADD CONSTRAINT "PUBLIC"."FKFIBUKM4H7DITN7FS0Y1TO8NBA" FOREIGN KEY("TAG_ID") REFERENCES "PUBLIC"."TAG"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."IWUSER_COMMENTS" ADD CONSTRAINT "PUBLIC"."FK2AT2LLN33OPEAJP19VJQKWWYW" FOREIGN KEY("COMMENTS_ID") REFERENCES "PUBLIC"."COMMENT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."TAG_COMMENT" ADD CONSTRAINT "PUBLIC"."FKG1G1XWMJ0WQCVPW9W3582UE6E" FOREIGN KEY("COMMENT_ID") REFERENCES "PUBLIC"."COMMENT"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."MENTORING_ALUMNOS" ADD CONSTRAINT "PUBLIC"."FKIMSWO64VK1KM8AUKT4MBSD6PL" FOREIGN KEY("ALUMNOS_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."COMMENT_TAG" ADD CONSTRAINT "PUBLIC"."FKRLUSE8H6W6YSN2Q9SREY5HWHA" FOREIGN KEY("COMMENT_ID") REFERENCES "PUBLIC"."COMMENT"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."IWUSER_REVIEW" ADD CONSTRAINT "PUBLIC"."FK5V4ONHNVEBEYRXPJ2J36JXDYA" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."IWUSER"("ID") NOCHECK; 
